
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      # imagePullSecrets:
      # - name: ecr-secret
      initContainers:
        - name: init-container
          image: 590999018668.dkr.ecr.us-east-1.amazonaws.com/demo-app:21
          command:
            - sh
            - -c
            - "echo \"Waiting for Postgres to be ready...\"\nuntil nc -z postgres 5432; do\n  echo \"Postgres is not ready yet. Retrying in 5 seconds...\"\n  sleep 5\ndone\necho \"Postgres is ready. Proceeding with the application startup.\"  \n"
      containers:
        - name: demo-app
          image: 590999018668.dkr.ecr.us-east-1.amazonaws.com/demo-app:21
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: postgres
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 3000
            initialDelaySeconds: 25
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 3000
            initialDelaySeconds: 25
            periodSeconds: 10
