```yaml
apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-app

spec:
  replicas: 2

  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app: demo-app

    spec:

      imagePullSecrets:
      - name: ecr-secret

      containers:
      - name: demo-app
        image: 590999018668.dkr.ecr.us-east-1.amazonaws.com/demo-app:14
        imagePullPolicy: Always

        env:
        - name: DB_HOST
          value: postgres

        ports:
        - containerPort: 3000

        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /health/live
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 10

---
apiVersion: v1
kind: Service

metadata:
  name: demo-app-service

spec:
  selector:
    app: demo-app

  ports:
  - port: 80
    targetPort: 3000

  type: NodePort
```
