name: CI Pipeline
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:

    Trivy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run Trivy scan
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            format: 'table'
            exit-code: '1'
            severity: 'CRITICAL,HIGH'
    gitleaks:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Run Gitleaks scan
          uses: zricethezav/gitleaks-action@v1.3.0
          with:
            args: "--path=. --verbose"
      synk:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'  
        - name: Install dependencies
          working-directory: ./app
          run: npm install
        
        - name: Run Snyk scan
          uses: snyk/actions/node@master
          with:
            args: --file=app/package.json
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    SonarQube:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up SonarQube
          uses: sonarsource/sonarqube-scan-action@v5
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >
              -Dsonar.projectKey=Demo-Challenge
              -Dsonar.host.url=http://18.204.228.177:9000/
    unit-tests:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '16'
        - name: Install dependencies
          working-directory: ./app
          run: npm install
        - name: Run unit tests
          working-directory: ./app
          run: npm test

    docker-build:
        runs-on: ubuntu-latest
        needs: [Trivy, gitleaks, SonarQube, unit-tests]
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Build Docker image
          run: docker build -t node-image:v1 .
        - name: Tag Docker image with Git SHA
          run: docker tag node-image:v1 ${{ vars.DOCKER_USERNAME }}/node-image:${{ github.sha }}
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Push Docker image
          run: docker push ${{ vars.DOCKER_USERNAME }}/node-image:${{ github.sha }}
    update-k8s-deployment:
        runs-on: ubuntu-latest
        needs: docker-build
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Install yq
          run: |
            sudo apt-get update
            sudo apt-get install -y yq
        - name: update image tag
          run: |
            yq e '.spec.template.spec.containers[0].image = "${{ vars.DOCKER_USERNAME }}/node-image:${{ github.sha }}"' -i k8smanifests/deploy.yml
        - name: git config
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
        - name: commit and push changes 
          run: |
            git add k8smanifests/deploy.yml
            git commit -m "Update image tag to ${{ github.sha }}" || true
            git push origin main    
